### ISSUE TITLE
x509: certificate signed by unknown authority with kubernetes

### ISSUE THREAD

**Issue by bpattewar** [att-comdev/halcyon-vagrant-kubernetes#49]
After running all the steps run inside the read.me doc and after running vagrant up
when I try to test Kubernetes Cluster, I am getting following issue
~/halcyon-vagrant-kubernetes$ kubectl run -i -t $(uuidgen) --image=busybox --restart=Never
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

I tried it several times and the issue is persistent. The base OS is Ubuntu16.04

**Comment by v1k0d3n** [comment]
@Bpatewar have you tried running a `vagrant box update` within the directory, so it forces the boxes to upgrade?

**Comment by v1k0d3n** [comment]
@Bpatewar just checking back with you. do you have any updates on this, so we can either resolve it or close the issue?

**Comment by v1k0d3n** [comment]
unfortunately no response. closing issue.
